version: '3.8'
services:
    php:
        build:
            context: php
            dockerfile: Dockerfile
        volumes:
            - ./php/src:/var/www/html/
        restart: always
        ports:
            - 1337:80
